server:
  port: 9000 # 端口

spring:
  application:
    name: zuul-provider # 应用名称

# 路由规则
zuul:
  # 禁用 Zuul 默认的异常处理 filter
  SendErrorFilter:
    error:
      disable: true
  routes:
    product-service:              # 路由 id 自定义
      path: /service-provider/**   # 配置请求 url 的映射路径
      serviceId: service-provider  # 根据 serviceId 自动从注册中心获取服务地址并转发请求
  prefix: /api

# 配置 Eureka Server 注册中心
eureka:
  instance:
    hostname: localhost              # 主机名，不配置的时候将根据操作系统的主机名来获取
  client:
    register-with-eureka: true   # 是否将自己注册到注册中心，默认为 true
    fetch-registry: true         # 是否从注册中心获取服务注册信息，默认为 true
    service-url:                  # 注册中心对外暴露的注册地址
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/