server:
  port: 9090 # 端口
  tomcat:
    max-threads: 10 # 降低最大线程数方便模拟高并发

spring:
  application:
    name: service-consumer # 应用名称
  # redis 缓存
  redis:
    timeout: 10000        # 连接超时时间
    host: 127.0.0.1       # Redis服务器地址
    port: 6379            # Redis服务器端口
    database: 0           # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024  # 最大连接数，默认 8
        max-wait: 10000   # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200     # 最大空闲连接，默认 8
        min-idle: 5       # 最小空闲连接，默认 0

# 配置 Eureka Server 注册中心
eureka:
  instance:
    hostname: localhost              # 主机名，不配置的时候将根据操作系统的主机名来获取
  client:
    register-with-eureka: true   # 是否将自己注册到注册中心，默认为 true
    fetch-registry: true         # 是否从注册中心获取服务注册信息，默认为 true
    service-url:                  # 注册中心对外暴露的注册地址
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000


